
name: CI

on:
  pull_request:
    branches:
      - '**'

  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'

      - name: Build & Test
        working-directory: ./windchill
        run: |
          go get .
          go build -v ./...
          go test -v